# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 538)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input = QtWidgets.QLineEdit(self.centralWidget)
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.br_in = QtWidgets.QPushButton(self.centralWidget)
        self.br_in.setObjectName("br_in")
        self.horizontalLayout.addWidget(self.br_in)
        self.cir_in = QtWidgets.QCheckBox(self.centralWidget)
        self.cir_in.setObjectName("cir_in")
        self.horizontalLayout.addWidget(self.cir_in)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.target = QtWidgets.QLineEdit(self.centralWidget)
        self.target.setClearButtonEnabled(False)
        self.target.setObjectName("target")
        self.horizontalLayout_3.addWidget(self.target)
        self.br_tar = QtWidgets.QPushButton(self.centralWidget)
        self.br_tar.setObjectName("br_tar")
        self.horizontalLayout_3.addWidget(self.br_tar)
        self.cir_tar = QtWidgets.QCheckBox(self.centralWidget)
        self.cir_tar.setObjectName("cir_tar")
        self.horizontalLayout_3.addWidget(self.cir_tar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.pr_fw = QtWidgets.QLineEdit(self.centralWidget)
        self.pr_fw.setObjectName("pr_fw")
        self.horizontalLayout_8.addWidget(self.pr_fw)
        self.enzyA = QtWidgets.QComboBox(self.centralWidget)
        self.enzyA.setCurrentText("")
        self.enzyA.setObjectName("enzyA")
        self.horizontalLayout_8.addWidget(self.enzyA)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.pr_fw_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.pr_fw_2.setObjectName("pr_fw_2")
        self.horizontalLayout_7.addWidget(self.pr_fw_2)
        self.enzyB = QtWidgets.QComboBox(self.centralWidget)
        self.enzyB.setCurrentText("")
        self.enzyB.setObjectName("enzyB")
        self.horizontalLayout_7.addWidget(self.enzyB)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 517, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionHelp_Menu = QtWidgets.QAction(MainWindow)
        self.actionHelp_Menu.setObjectName("actionHelp_Menu")
        self.menuHelp.addAction(self.actionHelp_Menu)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input.setPlaceholderText(_translate("MainWindow", "Sequence with Target Region"))
        self.br_in.setText(_translate("MainWindow", "Browse"))
        self.cir_in.setText(_translate("MainWindow", "Circular"))
        self.target.setPlaceholderText(_translate("MainWindow", "Target Vector"))
        self.br_tar.setText(_translate("MainWindow", "Browse"))
        self.cir_tar.setText(_translate("MainWindow", "Circular"))
        self.label_2.setText(_translate("MainWindow", "Forward"))
        self.pr_fw.setPlaceholderText(_translate("MainWindow", "Forward Primer"))
        self.label.setText(_translate("MainWindow", "Reverse"))
        self.pr_fw_2.setPlaceholderText(_translate("MainWindow", "Reverse Primer"))
        self.label_3.setText(_translate("MainWindow", "Choose Target Fragment:"))
        self.pushButton_2.setText(_translate("MainWindow", "Analytical Gel"))
        self.pushButton.setText(_translate("MainWindow", "Save Result"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHelp_Menu.setText(_translate("MainWindow", "Help Menu"))

