# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 658)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.enzyC = QtWidgets.QComboBox(self.centralWidget)
        self.enzyC.setEnabled(False)
        self.enzyC.setEditable(False)
        self.enzyC.setObjectName("enzyC")
        self.horizontalLayout_4.addWidget(self.enzyC)
        self.enzyD = QtWidgets.QComboBox(self.centralWidget)
        self.enzyD.setEnabled(False)
        self.enzyD.setObjectName("enzyD")
        self.horizontalLayout_4.addWidget(self.enzyD)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.frag_list = ComboBox(self.centralWidget)
        self.frag_list.setEnabled(True)
        self.frag_list.setObjectName("frag_list")
        self.verticalLayout.addWidget(self.frag_list)
        self.run = QtWidgets.QPushButton(self.centralWidget)
        self.run.setEnabled(True)
        self.run.setObjectName("run")
        self.verticalLayout.addWidget(self.run)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.digest_vec = QtWidgets.QPushButton(self.centralWidget)
        self.digest_vec.setObjectName("digest_vec")
        self.horizontalLayout_2.addWidget(self.digest_vec)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.save_vec = QtWidgets.QPushButton(self.centralWidget)
        self.save_vec.setObjectName("save_vec")
        self.horizontalLayout_2.addWidget(self.save_vec)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputs = QtWidgets.QLineEdit(self.groupBox)
        self.inputs.setObjectName("inputs")
        self.horizontalLayout.addWidget(self.inputs)
        self.br_in = QtWidgets.QPushButton(self.groupBox)
        self.br_in.setObjectName("br_in")
        self.horizontalLayout.addWidget(self.br_in)
        self.cir_in = QtWidgets.QCheckBox(self.groupBox)
        self.cir_in.setChecked(True)
        self.cir_in.setObjectName("cir_in")
        self.horizontalLayout.addWidget(self.cir_in)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.target = QtWidgets.QLineEdit(self.groupBox)
        self.target.setClearButtonEnabled(False)
        self.target.setObjectName("target")
        self.horizontalLayout_3.addWidget(self.target)
        self.br_tar = QtWidgets.QPushButton(self.groupBox)
        self.br_tar.setObjectName("br_tar")
        self.horizontalLayout_3.addWidget(self.br_tar)
        self.cir_tar = QtWidgets.QCheckBox(self.groupBox)
        self.cir_tar.setChecked(True)
        self.cir_tar.setObjectName("cir_tar")
        self.horizontalLayout_3.addWidget(self.cir_tar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.pr_fw = QtWidgets.QLineEdit(self.groupBox_2)
        self.pr_fw.setObjectName("pr_fw")
        self.horizontalLayout_8.addWidget(self.pr_fw)
        self.enzyA = QtWidgets.QComboBox(self.groupBox_2)
        self.enzyA.setCurrentText("")
        self.enzyA.setObjectName("enzyA")
        self.horizontalLayout_8.addWidget(self.enzyA)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.pr_rv = QtWidgets.QLineEdit(self.groupBox_2)
        self.pr_rv.setObjectName("pr_rv")
        self.horizontalLayout_7.addWidget(self.pr_rv)
        self.enzyB = QtWidgets.QComboBox(self.groupBox_2)
        self.enzyB.setCurrentText("")
        self.enzyB.setObjectName("enzyB")
        self.horizontalLayout_7.addWidget(self.enzyB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 582, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionHelp_Menu = QtWidgets.QAction(MainWindow)
        self.actionHelp_Menu.setObjectName("actionHelp_Menu")
        self.actionCheck_for_Updates = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_Updates.setObjectName("actionCheck_for_Updates")
        self.menuHelp.addAction(self.actionHelp_Menu)
        self.menuHelp.addAction(self.actionCheck_for_Updates)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Choose Target Fragment:"))
        self.checkBox.setText(_translate("MainWindow", "Cut with same as insert"))
        self.run.setText(_translate("MainWindow", "Run PCR, Digest and Ligation"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", "Status Messages and sequences will appear here."))
        self.digest_vec.setText(_translate("MainWindow", "Analytical Digest"))
        self.save_vec.setText(_translate("MainWindow", "Save Result"))
        self.groupBox.setTitle(_translate("MainWindow", "Input Sequences"))
        self.inputs.setPlaceholderText(_translate("MainWindow", "Sequence with Target Region"))
        self.br_in.setText(_translate("MainWindow", "Browse"))
        self.cir_in.setText(_translate("MainWindow", "Circular"))
        self.target.setPlaceholderText(_translate("MainWindow", "Target Vector"))
        self.br_tar.setText(_translate("MainWindow", "Browse"))
        self.cir_tar.setText(_translate("MainWindow", "Circular"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Primers"))
        self.label_2.setText(_translate("MainWindow", "Forward"))
        self.pr_fw.setPlaceholderText(_translate("MainWindow", "Forward Primer"))
        self.label.setText(_translate("MainWindow", "Reverse"))
        self.pr_rv.setPlaceholderText(_translate("MainWindow", "Reverse Primer"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHelp_Menu.setText(_translate("MainWindow", "Help Menu"))
        self.actionCheck_for_Updates.setText(_translate("MainWindow", "Check for Updates"))

from combobox import ComboBox
